#!/usr/bin/env python3
import os
import sys
import json
import subprocess
from datetime import datetime, UTC

def run_cmd(args, cwd=None, env=None, check=True):
    print(f"Running: {' '.join(args)}")
    result = subprocess.run(args, cwd=cwd, env=env, capture_output=True, text=True)
    if result.returncode != 0 and check:
        print(f"Command failed with code {result.returncode}")
        print(f"Stdout:\n{result.stdout}")
        print(f"Stderr:\n{result.stderr}")
        sys.exit(result.returncode)
    return result

def main():
    intent_json_path = "/tmp/intent.json"
    if not os.path.exists(intent_json_path):
        print(f"Error: {intent_json_path} does not exist.")
        sys.exit(1)
        
    with open(intent_json_path, 'r') as f:
        intent_data = json.load(f)
        
    description = intent_data.get('description', 'No description provided')
    goal = intent_data.get('goal', 'No goal provided')
    slug = intent_data.get('slug', '')
    branch = intent_data.get('branch')
    
    if not branch:
        if not slug:
            print("Error: Either 'branch' or 'slug' must be provided in intent JSON.")
            sys.exit(1)
        import re
        # Convert any space to '-' and collapse consecutive hyphens
        slug_clean = slug.replace(" ", "-")
        slug_clean = re.sub(r'-+', '-', slug_clean)
        
        import time
        branch = f"I-{int(time.time())}-{slug_clean}"
        intent_data['branch'] = branch
        intent_data['slug'] = slug_clean
        
    intent_branch = f"{branch}/_"
    
    target_branch = intent_data.get('target_branch', 'main')
    
    repo_dir = os.path.expanduser("~/repo")
    os.makedirs(repo_dir, exist_ok=True)
    
    # Clone the repo
    repo_url = "git@github.com:Holon-Agentic-Coder/holon-agentic-coder-ref.git"
    run_cmd(["git", "clone", "--branch", target_branch, "--single-branch", "--depth", "1", repo_url, "."], cwd=repo_dir)
    
    # Checkout intent branch
    run_cmd(["git", "checkout", "-B", intent_branch, f"origin/{target_branch}"], cwd=repo_dir)
    
    # Update intents.jsonl
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    intent_data['status'] = 'proposed'
    intent_data['created_at'] = timestamp
    
    ledger_dir = os.path.join(repo_dir, "holon-knowledge/ledger")
    os.makedirs(ledger_dir, exist_ok=True)
    intents_file_path = os.path.join(ledger_dir, "intents.jsonl")
    
    with open(intents_file_path, "a") as lf:
        lf.write(json.dumps(intent_data) + "\n")
        
    commit_msg = (
        f"intent: created {intent_branch}\n\n"
        f"Description:\n{description}\n\n"
        f"Goal:\n{goal}\n\n"
        f"Generated by Holon Intent Agent at {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
    )
    
    # Git commit & push
    run_cmd(["git", "add", "holon-knowledge/ledger/intents.jsonl"], cwd=repo_dir)
    run_cmd(["git", "config", "--local", "user.email", "intent-agent@holon-agentic-coder.com"], cwd=repo_dir)
    run_cmd(["git", "config", "--local", "user.name", "Holon Intent Agent"], cwd=repo_dir)
    run_cmd(["git", "commit", "-m", commit_msg], cwd=repo_dir)
    run_cmd(["git", "push", "-u", "origin", intent_branch], cwd=repo_dir)
    
    print(f"Intent branch '{intent_branch}' created and intent logged.")

if __name__ == "__main__":
    main()
